### ISSUE TITLE
Add support for flag value auto-completion

### ISSUE THREAD

**Issue by codyaray** [thediveo/enumflag#5]
This looks like a great library. One thing I noticed missing was support for flag auto-completion with cobra.

This SO answer shows a good example of how that can be implemented: https://stackoverflow.com/a/70541824/337735

(Incidentally I found your library on this SO answer too. And here you are! https://stackoverflow.com/questions/50824554/permitted-flag-values-for-cobra#comment133213356_73297333 :))

**Comment by thediveo** [comment]
Hi codyaray, thank you very much for your feature request and already including useful references!

After checking the (somewhat minimalist) documentation and then consulting cobra's code I'm wondering how to best make this new feature convenient to use to module users.

My idea is as follows:

    ef := enumflag.New(..., FooModeIds, ...)
    cmd.PersistentFlags().VarP(..., ef, ...)
    ef.Completion(cmd, FooModeCompletions)

where

    FooModeCompletions := map[FooMode]string{...}

While I would like to provide a new, additional "constructor" along the lines of

    ef := enumflag.NewWithCompletions(..., FooModeIds, FooModeCompls, ...)

the way cobra's API work is that this cannot do the registration on its own, because that needs to be done on the command and the new flag hasn't yet been added. 

Any thoughts?

**Comment by thediveo** [comment]
Implemented in v2.0.4, please see the README.md for a short new section on shell completion.
